// [{
//   "id": 1,
//   "first_name": "Leigh",
//   "last_name": "Haig",
//   "email": "lhaig0@earthlink.net",
//   "gender": "Female",
//   "ip_address": "136.44.140.55"
// }, {
//   "id": 2,
//   "first_name": "Wally",
//   "last_name": "Blaydes",
//   "email": "wblaydes1@twitpic.com",
//   "gender": "Male",
//   "ip_address": "92.91.38.159"
// }, {
//   "id": 3,
//   "first_name": "Dur",
//   "last_name": "De Giovanni",
//   "email": "ddegiovanni2@sohu.com",
//   "gender": "Male",
//   "ip_address": "226.188.80.138"
// }, {
//   "id": 4,
//   "first_name": "Almeria",
//   "last_name": "Ollerhad",
//   "email": "aollerhad3@histats.com",
//   "gender": "Female",
//   "ip_address": "122.55.24.75"
// }, {
//   "id": 5,
//   "first_name": "Grantley",
//   "last_name": "Andrusyak",
//   "email": "gandrusyak4@godaddy.com",
//   "gender": "Male",
//   "ip_address": "108.244.31.138"
// }, {
//   "id": 6,
//   "first_name": "Karlotta",
//   "last_name": "Jahnig",
//   "email": "kjahnig5@51.la",
//   "gender": "Female",
//   "ip_address": "212.202.205.142"
// }, {
//   "id": 7,
//   "first_name": "Rita",
//   "last_name": "Shiril",
//   "email": "rshiril6@hugedomains.com",
//   "gender": "Female",
//   "ip_address": "172.185.135.186"
// }, {
//   "id": 8,
//   "first_name": "Tara",
//   "last_name": "Ivons",
//   "email": "tivons7@bizjournals.com",
//   "gender": "Female",
//   "ip_address": "95.150.194.212"
// }, {
//   "id": 9,
//   "first_name": "Danny",
//   "last_name": "Masurel",
//   "email": "dmasurel8@wikimedia.org",
//   "gender": "Female",
//   "ip_address": "80.97.59.227"
// }, {
//   "id": 10,
//   "first_name": "Gradey",
//   "last_name": "Wrist",
//   "email": "gwrist9@japanpost.jp",
//   "gender": "Male",
//   "ip_address": "232.80.237.151"
// }, {
//   "id": 11,
//   "first_name": "Drusie",
//   "last_name": "Manhare",
//   "email": "dmanharea@illinois.edu",
//   "gender": "Female",
//   "ip_address": "173.239.11.213"
// }, {
//   "id": 12,
//   "first_name": "Klemens",
//   "last_name": "Trainor",
//   "email": "ktrainorb@walmart.com",
//   "gender": "Male",
//   "ip_address": "207.120.219.2"
// }, {
//   "id": 13,
//   "first_name": "Flinn",
//   "last_name": "McTear",
//   "email": "fmctearc@pagesperso-orange.fr",
//   "gender": "Genderfluid",
//   "ip_address": "224.38.74.65"
// }, {
//   "id": 14,
//   "first_name": "Eleanor",
//   "last_name": "Inde",
//   "email": "einded@marketwatch.com",
//   "gender": "Non-binary",
//   "ip_address": "131.157.137.10"
// }, {
//   "id": 15,
//   "first_name": "Curry",
//   "last_name": "Camsey",
//   "email": "ccamseye@google.ca",
//   "gender": "Male",
//   "ip_address": "72.136.15.159"
// }, {
//   "id": 16,
//   "first_name": "Gilbertine",
//   "last_name": "Ferenc",
//   "email": "gferencf@paginegialle.it",
//   "gender": "Female",
//   "ip_address": "253.192.226.1"
// }, {
//   "id": 17,
//   "first_name": "Alina",
//   "last_name": "Voase",
//   "email": "avoaseg@nifty.com",
//   "gender": "Polygender",
//   "ip_address": "125.176.164.188"
// }, {
//   "id": 18,
//   "first_name": "Gabrielle",
//   "last_name": "Featherstonehaugh",
//   "email": "gfeatherstonehaughh@cbsnews.com",
//   "gender": "Female",
//   "ip_address": "124.120.52.157"
// }, {
//   "id": 19,
//   "first_name": "Fred",
//   "last_name": "Devlin",
//   "email": "fdevlini@amazon.co.uk",
//   "gender": "Female",
//   "ip_address": "242.30.108.72"
// }, {
//   "id": 20,
//   "first_name": "Stephanie",
//   "last_name": "Ferrey",
//   "email": "sferreyj@google.it",
//   "gender": "Female",
//   "ip_address": "2.109.124.184"
// }]


export const url= "https://www.gstatic.com/marketing-cms/assets/images/1a/9f/7bba006e49de847508df3a4a7b93/andriod-full-body.webp=s96-fcrop64=1,00000000ffffffff-rw"

export const navItems=['Home','About','Contact','Blogs', 'Courses']